language: csharp
solution: FredBotNETCore.sln
install:
  - cd src
  - curl -L -o nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - ls
  - mono nuget.exe restore FredBotNETCore.sln -Verbosity Detailed -NonInteractive -ConfigFile nuget.config
